const DATA=window.NL_DATA,$=id=>document.getElementById(id),base=$('base'),overlay=$('overlay'),bctx=base.getContext('2d'),octx=overlay.getContext('2d');
function decodeU16(s){const bin=atob(s),out=new Uint16Array(bin.length/2);for(let i=0,j=0;i<bin.length;i+=2,j++)out[j]=bin.charCodeAt(i)|(bin.charCodeAt(i+1)<<8);return out}
const DIST=decodeU16(DATA.distanceB64),TIME=decodeU16(DATA.timeB64),names=DATA.communities,N=names.length,nameIndex=new Map(names.map((n,i)=>[n.toLowerCase(),i])),special=DATA.specialRoutes||{};
$('towns').innerHTML=names.map(n=>`<option value="${n.replaceAll('&','&amp;').replaceAll('"','&quot;')}"></option>`).join('');
const adj=Array.from({length:DATA.nodes.length},()=>[]);DATA.edges.forEach((e,ei)=>{adj[e[0]].push([e[1],e[2],ei]);adj[e[1]].push([e[0],e[2],ei])});
const edgeBounds=DATA.edges.map(e=>{let a=Infinity,b=Infinity,c=-Infinity,d=-Infinity;for(const p of e[3]){a=Math.min(a,p[0]);b=Math.min(b,p[1]);c=Math.max(c,p[0]);d=Math.max(d,p[1])}return[a,b,c,d]});
class Heap{constructor(){this.a=[]}push(x){const a=this.a;a.push(x);let i=a.length-1;while(i){const p=(i-1)>>1;if(a[p][0]<=x[0])break;a[i]=a[p];i=p}a[i]=x}pop(){const a=this.a;if(!a.length)return null;const r=a[0],x=a.pop();if(a.length){let i=0;while(true){const l=i*2+1;if(l>=a.length)break;const rr=l+1,c=rr<a.length&&a[rr][0]<a[l][0]?rr:l;if(a[c][0]>=x[0])break;a[i]=a[c];i=c}a[i]=x}return r}get size(){return this.a.length}}
function dijkstra(s,t){if(s===t)return[];const dist=new Float64Array(adj.length);dist.fill(Infinity);const pn=new Int32Array(adj.length),pe=new Int32Array(adj.length);pn.fill(-1);pe.fill(-1);dist[s]=0;const h=new Heap();h.push([0,s]);while(h.size){const [d,u]=h.pop();if(d!==dist[u])continue;if(u===t)break;for(const [v,w,e] of adj[u]){const nd=d+w;if(nd<dist[v]){dist[v]=nd;pn[v]=u;pe[v]=e;h.push([nd,v])}}}if(!isFinite(dist[t]))return null;const es=[];let u=t;while(u!==s){if(pe[u]<0)return null;es.push(pe[u]);u=pn[u]}return es.reverse()}
function kmBetween(a,b){const lat=(a[1]+b[1])*Math.PI/360,dx=(b[0]-a[0])*111.32*Math.cos(lat),dy=(b[1]-a[1])*111.32;return Math.hypot(dx,dy)}
function edgeKm(es){return(es||[]).reduce((s,ei)=>s+(DATA.edges[ei][2]||0),0)}
function nearestNode(lon,lat){let best=-1,bd=Infinity;const c=Math.cos(lat*Math.PI/180);for(let i=0;i<DATA.nodes.length;i++){const p=DATA.nodes[i],dx=(p[0]-lon)*111.32*c,dy=(p[1]-lat)*111.32,d=dx*dx+dy*dy;if(d<bd){bd=d;best=i}}return{node:best,distanceKm:Math.sqrt(bd)}}
function nearestCommunity(lon,lat){let bi=-1,bd=Infinity;const c=Math.cos(lat*Math.PI/180);for(let i=0;i<N;i++){const a=DATA.anchors[i];if(a==null||a<0)continue;const p=DATA.nodes[a],dx=(p[0]-lon)*111.32*c,dy=(p[1]-lat)*111.32,d=dx*dx+dy*dy;if(d<bd){bd=d;bi=i}}return{index:bi,distanceKm:Math.sqrt(bd)}}
let routeSegments=[],routeCoords=[],routeDist=0,routeTime=0,routeCum=[],routePolylineKm=0,progress=0,gpsWatch=null,gpsPosition=null,followGPS=false,drag=null,originMode='town',originGPS=null,currentDestIndex=-1,rafPan=0,gpsLastFixAt=0,gpsStaleTimer=null,wakeLock=null,gpsPermission='unknown',gpsRunning=false,offlinePackageReady=false,lastGpsAppliedAt=0,deferredInstall=null;
let etaModel={movingKm:0,speedKmh:null,lastProgress:null,lastTs:null};let view={minx:DATA.bounds[0],miny:DATA.bounds[1],maxx:DATA.bounds[2],maxy:DATA.bounds[3]};
function setStatus(text,warn=false){$('statusText').textContent=text;$('status').classList.toggle('warn',warn)}
function restoreTripPrefs(){try{const d=localStorage.getItem('nl-offline-destination'),o=localStorage.getItem('nl-offline-origin');if(d&&nameIndex.has(d.toLowerCase()))$('to').value=d;if(o&&nameIndex.has(o.toLowerCase()))$('from').value=o}catch(e){}}
function saveTripPrefs(){try{const d=$('to').value.trim();if(nameIndex.has(d.toLowerCase()))localStorage.setItem('nl-offline-destination',d);if(originMode!=='gps'){const o=$('from').value.trim();if(nameIndex.has(o.toLowerCase()))localStorage.setItem('nl-offline-origin',o)}}catch(e){}}

function resize(c,ctx){const dpr=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect();c.width=Math.max(1,Math.round(r.width*dpr));c.height=Math.max(1,Math.round(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)}function size(){resize(base,bctx);resize(overlay,octx);renderBase();renderOverlay()}
function project(lon,lat){const w=base.clientWidth,h=base.clientHeight,p=15,sx=(w-2*p)/(view.maxx-view.minx),sy=(h-2*p)/(view.maxy-view.miny),s=Math.min(sx,sy),ox=(w-(view.maxx-view.minx)*s)/2,oy=(h-(view.maxy-view.miny)*s)/2;return[ox+(lon-view.minx)*s,h-(oy+(lat-view.miny)*s)]}
function visible(bb){return!(bb[2]<view.minx||bb[0]>view.maxx||bb[3]<view.miny||bb[1]>view.maxy)}
function renderBase(){bctx.clearRect(0,0,base.clientWidth,base.clientHeight);bctx.lineJoin='round';bctx.lineCap='round';for(const type of ['road','ferry']){bctx.beginPath();for(let ei=0;ei<DATA.edges.length;ei++){const e=DATA.edges[ei];if(!visible(edgeBounds[ei])||(e[4]||'road')!==type)continue;for(let i=0;i<e[3].length;i++){const q=project(e[3][i][0],e[3][i][1]);i?bctx.lineTo(q[0],q[1]):bctx.moveTo(q[0],q[1])}}bctx.strokeStyle=type==='ferry'?'#496b7d':'#29404d';bctx.globalAlpha=type==='ferry'?.82:.62;bctx.lineWidth=type==='ferry'?1.2:.68;if(type==='ferry')bctx.setLineDash([4,4]);bctx.stroke();bctx.setLineDash([])}bctx.globalAlpha=1;renderCommunityLabels()}
function renderCommunityLabels(){const span=view.maxx-view.minx;if(span>3.2)return;const occupied=new Set(),maxLabels=span<.7?42:span<1.5?28:18;let shown=0;bctx.font='600 10px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';for(let i=0;i<N&&shown<maxLabels;i++){const a=DATA.anchors[i];if(a==null||a<0)continue;const p=DATA.nodes[a];if(!p||p[0]<view.minx||p[0]>view.maxx||p[1]<view.miny||p[1]>view.maxy)continue;const q=project(p[0],p[1]),cell=Math.floor(q[0]/85)+','+Math.floor(q[1]/24);if(occupied.has(cell))continue;occupied.add(cell);bctx.beginPath();bctx.arc(q[0],q[1],2.1,0,Math.PI*2);bctx.fillStyle='#6f8b9b';bctx.fill();bctx.lineWidth=3;bctx.strokeStyle='rgba(5,15,23,.92)';bctx.fillStyle='#a9bbc5';bctx.strokeText(names[i],q[0]+5,q[1]-4);bctx.fillText(names[i],q[0]+5,q[1]-4);shown++}}
function drawSegment(ctx,s){const c=s.coords;if(!c||c.length<2)return;ctx.beginPath();for(let i=0;i<c.length;i++){const q=project(c[i][0],c[i][1]);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])}ctx.strokeStyle=s.type==='virtual'?'#a4dfbd':'#61df97';ctx.lineWidth=s.type==='virtual'?3.2:4.4;ctx.lineJoin='round';ctx.lineCap='round';if(s.type==='virtual')ctx.setLineDash([10,7]);ctx.stroke();ctx.setLineDash([])}
function marker(p,label,kind){if(!p)return;const q=project(p[0],p[1]);if(kind==='gps'&&gpsPosition&&gpsPosition.accuracy){const q2=project(p[0]+.01,p[1]),pxPerKm=Math.abs(q2[0]-q[0])/(.01*111.32*Math.cos(p[1]*Math.PI/180)||1),r=Math.min(38,Math.max(8,(gpsPosition.accuracy/1000)*pxPerKm));octx.beginPath();octx.arc(q[0],q[1],r,0,Math.PI*2);octx.fillStyle='rgba(116,188,255,.13)';octx.fill();octx.strokeStyle='rgba(116,188,255,.25)';octx.lineWidth=1;octx.stroke()}octx.beginPath();octx.arc(q[0],q[1],kind==='gps'?7:6,0,Math.PI*2);octx.fillStyle=kind==='gps'?'#74bcff':kind==='dest'?'#61df97':'#f6f8fa';octx.fill();octx.lineWidth=kind==='gps'?3:2;octx.strokeStyle='#061019';octx.stroke();if(label){octx.font='650 11px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';octx.fillStyle='#f6f8fa';octx.strokeStyle='rgba(6,16,25,.95)';octx.lineWidth=4;octx.strokeText(label,q[0]+9,q[1]-9);octx.fillText(label,q[0]+9,q[1]-9)}}
function renderOverlay(){octx.clearRect(0,0,overlay.clientWidth,overlay.clientHeight);for(const s of routeSegments)drawSegment(octx,s);if(routeCoords.length){const startLabel=originMode==='gps'?'Current location':$('from').value.trim();marker(routeCoords[0],startLabel,'start');marker(routeCoords.at(-1),$('to').value.trim(),'dest');const p=gpsPosition?[gpsPosition.lon,gpsPosition.lat]:pointAt(progress);marker(p,'','gps')}}
function fit(coords){if(!coords.length)return;let minx=Infinity,miny=Infinity,maxx=-Infinity,maxy=-Infinity;for(const p of coords){minx=Math.min(minx,p[0]);maxx=Math.max(maxx,p[0]);miny=Math.min(miny,p[1]);maxy=Math.max(maxy,p[1])}const dx=Math.max(maxx-minx,.02),dy=Math.max(maxy-miny,.02);view={minx:minx-dx*.14,maxx:maxx+dx*.14,miny:miny-dy*.14,maxy:maxy+dy*.14};renderBase();renderOverlay()}
function zoom(f){const cx=(view.minx+view.maxx)/2,cy=(view.miny+view.maxy)/2,dx=(view.maxx-view.minx)*f/2,dy=(view.maxy-view.miny)*f/2;view={minx:cx-dx,maxx:cx+dx,miny:cy-dy,maxy:cy+dy};renderBase();renderOverlay()}
function centerAt(lon,lat){const dx=(view.maxx-view.minx)/2,dy=(view.maxy-view.miny)/2;view={minx:lon-dx,maxx:lon+dx,miny:lat-dy,maxy:lat+dy};renderBase();renderOverlay()}
function addRoad(es,reverse=false){if(es==null)throw new Error('network components do not connect');let seq=reverse?es.slice().reverse():es.slice(),groups=[],cur=null;for(const ei of seq){const e=DATA.edges[ei],raw=e[4]||'road',type=(raw==='road')?'road':'virtual';let c=e[3].map(p=>[p[0],p[1]]);if(reverse)c.reverse();if(cur&&cur.type===type){const last=cur.coords.at(-1),a=c[0],b=c.at(-1),d0=(last[0]-a[0])**2+(last[1]-a[1])**2,d1=(last[0]-b[0])**2+(last[1]-b[1])**2;if(d1<d0)c.reverse();if((last[0]-c[0][0])**2+(last[1]-c[0][1])**2<1e-8)c=c.slice(1);cur.coords.push(...c);cur.edgeCount++}else{cur={type,coords:c,edgeCount:1,label:raw==='ferry'?'Ferry segment':raw==='virtual'?'Schematic network connection':''};groups.push(cur)}}routeSegments.push(...groups)}
function addVirtual(a,b,label){routeSegments.push({type:'virtual',coords:[[a[0],a[1]],[b[0],b[1]]],label})}
function gatewayNode(name){const i=nameIndex.get(name.toLowerCase());return i==null?-1:DATA.anchors[i]}
function remotePoint(name){const s=special[name];return s?[s.lon,s.lat]:null}
function composePath(originName,destName,a,b){routeSegments=[];const sa=special[originName],sb=special[destName],aa=DATA.anchors[a],bb=DATA.anchors[b];if(!sa&&!sb){addRoad(dijkstra(aa,bb));return}if(sa&&sb&&((originName==='Francois'&&destName==='Grey River')||(originName==='Grey River'&&destName==='Francois'))){addVirtual(remotePoint(originName),remotePoint(destName),'Direct remote ferry');return}const startNode=sa?gatewayNode(sa.gateway):aa,endNode=sb?gatewayNode(sb.gateway):bb;if(startNode<0||endNode<0)throw new Error('gateway anchor unavailable');if(sa)addVirtual(remotePoint(originName),DATA.nodes[startNode],sa.label);const road=dijkstra(startNode,endNode);if(road&&road.length)addRoad(road);if(sb)addVirtual(DATA.nodes[endNode],remotePoint(destName),sb.label)}
function composeFromNode(startNode,destName,b,originPoint){routeSegments=[];const sb=special[destName],endNode=sb?gatewayNode(sb.gateway):DATA.anchors[b];if(endNode<0)throw new Error('destination anchor unavailable');if(originPoint&&kmBetween(originPoint,DATA.nodes[startNode])>.03)addVirtual(originPoint,DATA.nodes[startNode],'GPS to road');const road=dijkstra(startNode,endNode);if(road&&road.length)addRoad(road);if(sb)addVirtual(DATA.nodes[endNode],remotePoint(destName),sb.label)}
function graphKmToDestination(startNode,destName,b){const sb=special[destName],endNode=sb?gatewayNode(sb.gateway):DATA.anchors[b],es=dijkstra(startNode,endNode);if(es==null)return null;let k=edgeKm(es);if(sb)k+=kmBetween(DATA.nodes[endNode],remotePoint(destName));return k}
function flattenSegments(){const out=[];for(const s of routeSegments){let c=s.coords.map(p=>[p[0],p[1]]);if(out.length&&c.length){const last=out.at(-1),a=c[0],b=c.at(-1),d0=(last[0]-a[0])**2+(last[1]-a[1])**2,d1=(last[0]-b[0])**2+(last[1]-b[1])**2;if(d1<d0)c.reverse();if((last[0]-c[0][0])**2+(last[1]-c[0][1])**2<1e-8)c=c.slice(1)}out.push(...c)}return out}
function metrics(){routeCum=[0];let total=0;for(let i=1;i<routeCoords.length;i++){total+=kmBetween(routeCoords[i-1],routeCoords[i]);routeCum.push(total)}routePolylineKm=total}
function pointAt(f){if(!routeCoords.length)return null;const target=routePolylineKm*f;let i=1;while(i<routeCum.length&&routeCum[i]<target)i++;if(i>=routeCum.length)return routeCoords.at(-1);const a=routeCoords[i-1],b=routeCoords[i],den=Math.max(routeCum[i]-routeCum[i-1],1e-9),t=(target-routeCum[i-1])/den;return[a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t]}
function snap(lon,lat){if(routeCoords.length<2)return null;let bd=Infinity,along=0;for(let i=1;i<routeCoords.length;i++){const a=routeCoords[i-1],b=routeCoords[i],sl=111.32*Math.cos((lat+(a[1]+b[1])/2)*Math.PI/360),ax=a[0]*sl,ay=a[1]*111.32,bx=b[0]*sl,by=b[1]*111.32,px=lon*sl,py=lat*111.32,vx=bx-ax,vy=by-ay,len=vx*vx+vy*vy;let t=len?((px-ax)*vx+(py-ay)*vy)/len:0;t=Math.max(0,Math.min(1,t));const qx=ax+t*vx,qy=ay+t*vy,d=(px-qx)**2+(py-qy)**2;if(d<bd){bd=d;along=routeCum[i-1]+(routeCum[i]-routeCum[i-1])*t}}return{fraction:Math.max(0,Math.min(1,along/Math.max(routePolylineKm,.0001))),distanceKm:Math.sqrt(bd)}}
function fmtMin(m){m=Math.round(Math.max(0,m));const h=Math.floor(m/60),mm=m%60;return h?`${h}h ${String(mm).padStart(2,'0')}m`:`${mm} min`}
function resetEta(){etaModel={movingKm:0,speedKmh:null,lastProgress:null,lastTs:null}}
function trackPace(newProgress,ts,gpsSpeedMps=null){if(gpsSpeedMps!=null&&isFinite(gpsSpeedMps)&&gpsSpeedMps>=1.5&&gpsSpeedMps<=55){const gv=gpsSpeedMps*3.6;etaModel.speedKmh=etaModel.speedKmh==null?gv:etaModel.speedKmh*.82+gv*.18}if(etaModel.lastProgress!=null&&etaModel.lastTs!=null){const dk=routeDist*(newProgress-etaModel.lastProgress),hours=(ts-etaModel.lastTs)/3600000;if(dk>.02&&hours>0){const v=dk/hours;if(v>=4&&v<=150){etaModel.movingKm+=dk;etaModel.speedKmh=etaModel.speedKmh==null?v:etaModel.speedKmh*.84+v*.16}}}etaModel.lastProgress=newProgress;etaModel.lastTs=ts}
function remainingMinutes(){const baseline=routeTime*(1-progress);if(!etaModel.speedKmh||etaModel.movingKm<2)return baseline;const observed=(routeDist*(1-progress))/etaModel.speedKmh*60,w=Math.min(.65,etaModel.movingKm/45*.65);return baseline*(1-w)+observed*w}
function update(){const rem=routeDist*(1-progress),rm=remainingMinutes();$('remaining').textContent=routeDist?Math.round(rem)+' km':'—';$('eta').textContent=routeTime?new Date(Date.now()+rm*60000).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';$('etaCaption').textContent=etaModel.speedKmh&&etaModel.movingKm>=2?'live arrival':'arrival';$('progressText').textContent=Math.round(progress*100)+'% complete';$('travelled').textContent=routeDist?Math.round(routeDist*progress)+' km':'—';$('fill').style.width=(progress*100)+'%';$('slider').value=Math.round(progress*1000);renderOverlay()}
function setTownLabels(){ $('distanceLabel').textContent='Official distance';$('timeLabel').textContent='Official time';$('distanceNote').textContent='NL-RDDb';$('timeNote').textContent='NL-RDDb';$('tripModeHint').textContent='Official town-to-town estimate'}
function setGpsLabels(nearName){$('distanceLabel').textContent='Estimated distance';$('timeLabel').textContent='Estimated time';$('distanceNote').textContent=`Calibrated near ${nearName}`;$('timeNote').textContent=`Calibrated near ${nearName}`;$('tripModeHint').textContent='Current road position → destination'}
function makeTrip(){stopGPS(false);saveTripPrefs();const av=$('from').value.trim(),bv=$('to').value.trim(),b=nameIndex.get(bv.toLowerCase());if(b==null){setStatus('Choose a Newfoundland & Labrador destination from the list.',true);return}currentDestIndex=b;if(originMode!=='gps'){const a=nameIndex.get(av.toLowerCase());if(a==null){setStatus('Choose an origin from the list, or use current location.',true);return}if(a===b){setStatus('Origin and destination must be different.',true);return}routeDist=DIST[a*N+b];routeTime=TIME[a*N+b];setTownLabels();buildTown(av,bv,a,b);return}if(!originGPS){setStatus('Current location has not been captured yet.',true);return}buildGps(bv,b)}
function busy(on){$('go').disabled=on;$('go').textContent=on?'Calculating…':'Show trip'}
function finishPath(virtual,statusText){routeCoords=flattenSegments();if(routeCoords.length<2)throw new Error('empty path');metrics();fit(routeCoords);$('routeNote').textContent=virtual?'Ferry / remote leg':'Road path';$('routeStatus').textContent=virtual?'Mixed':'On road';setStatus(statusText);progress=0;resetEta();update()}
function buildTown(av,bv,a,b){$('destination').textContent=bv;$('distance').textContent=routeDist?routeDist+' km':'—';$('time').textContent=routeTime?fmtMin(routeTime):'—';routeSegments=[];routeCoords=[];progress=0;resetEta();update();busy(true);setStatus('Calculating path locally…');setTimeout(()=>{try{composePath(av,bv,a,b);const virtual=routeSegments.some(s=>s.type==='virtual');const count=routeSegments.reduce((n,s)=>n+(s.edgeCount||0),0);finishPath(virtual,`Offline path ready · ${count||'special'} network segments.`)}catch(e){setStatus('Official trip data is available, but the map path could not be connected.',true)}finally{busy(false)}},10)}
function buildGps(bv,b){return new Promise(resolve=>{$('destination').textContent=bv;busy(true);setStatus('Routing from your road position…');setTimeout(()=>{let ok=false;try{const nn=nearestNode(originGPS.lon,originGPS.lat),nc=nearestCommunity(originGPS.lon,originGPS.lat);if(nn.node<0||nc.index<0)throw new Error('no nearby network');composeFromNode(nn.node,bv,b,[originGPS.lon,originGPS.lat]);routeCoords=flattenSegments();metrics();const baseStart=DATA.anchors[nc.index],baseGraph=graphKmToDestination(baseStart,bv,b),curGraph=graphKmToDestination(nn.node,bv,b);const od=DIST[nc.index*N+b],ot=TIME[nc.index*N+b];if(!baseGraph||!curGraph||!od||!ot)throw new Error('calibration unavailable');const ratio=Math.max(.08,Math.min(2.5,curGraph/baseGraph));routeDist=Math.max(0.1,od*ratio+nn.distanceKm);routeTime=Math.max(1,ot*ratio);setGpsLabels(names[nc.index]);$('distance').textContent=Math.round(routeDist)+' km';$('time').textContent=fmtMin(routeTime);const virtual=routeSegments.some(s=>s.type==='virtual');fit(routeCoords);$('routeNote').textContent=virtual?'Ferry / remote leg':'Road path';$('routeStatus').textContent=virtual?'Mixed':'On road';progress=0;gpsPosition={lon:originGPS.lon,lat:originGPS.lat,accuracy:originGPS.accuracy};resetEta();update();setStatus(`Current location routed · nearest reference: ${names[nc.index]} (${nc.distanceKm.toFixed(1)} km).`);ok=true}catch(e){setStatus('Could not connect current location to the offline road network.',true)}finally{busy(false);resolve(ok)}},10)})}
async function swMessage(type,timeout=45000){if(!('serviceWorker'in navigator)||!window.isSecureContext)return null;const reg=await navigator.serviceWorker.ready,worker=reg.active||reg.waiting||reg.installing;if(!worker)return null;return await new Promise(resolve=>{const ch=new MessageChannel(),timer=setTimeout(()=>resolve(null),timeout);ch.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data)};worker.postMessage({type},[ch.port2])})}
async function verifyOfflinePackage(force=false){if(!window.isSecureContext||!('serviceWorker'in navigator)){offlinePackageReady=false;updateRoadReadiness();return false}try{const r=await swMessage(force?'PREPARE_OFFLINE':'CACHE_STATUS',60000);offlinePackageReady=!!r?.ready;updateRoadReadiness(r);return offlinePackageReady}catch(e){offlinePackageReady=false;updateRoadReadiness({error:e.message});return false}}
async function requestPersistentStorage(){try{if(navigator.storage?.persist)return await navigator.storage.persist()}catch(e){}return false}
function installInstructions(){if(standaloneMode())return 'Installed on Home Screen.';if(deferredInstall)return 'Install is available on this device.';const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);return ios?'On iPhone/iPad: Share → Add to Home Screen after this page is on HTTPS.':'Install from your browser menu after this page is on HTTPS.'}
function updateRoadReadiness(cacheResult=null){const secure=window.isSecureContext,cache=offlinePackageReady,standalone=standaloneMode(),gpsOk=gpsPermission!=='denied'&&!!navigator.geolocation;let text='';let cls='';if(!secure){text='Needs HTTPS before phone GPS can work.';cls='warn'}else if(!cache){text=cacheResult?.error?`Offline package incomplete: ${cacheResult.error}`:'Offline package is still being verified.';cls='warn'}else if(gpsPermission==='denied'){text='Offline data is ready, but Location permission is denied.';cls='warn'}else{text=`Offline package ready · GPS ${gpsPermission==='granted'?'permission granted':'available'}${standalone?' · installed':''}.`;cls='good'}$('roadReadyDetail').textContent=text;$('roadReadyDetail').className='readydetail '+cls;$('installHint').textContent=installInstructions();const b=$('prepareRoad');b.textContent=secure&&cache?'Recheck road setup':'Prepare for road';const appBadge=$('appBadge');if(secure&&cache&&gpsPermission!=='denied'){appBadge.textContent=navigator.onLine?'● ROAD READY':'● OFFLINE READY';appBadge.classList.remove('warn')}}
async function prepareForRoad(){const b=$('prepareRoad');b.disabled=true;b.textContent='Preparing…';setStatus('Preparing the complete offline package…');try{await requestPersistentStorage();const cache=await verifyOfflinePackage(true);await refreshGpsPermission();if(!cache){setStatus('Offline package did not finish caching. Stay online and try again.',true);return}const blocked=gpsBlockReason();if(blocked){setStatus(blocked,true);return}setStatus('Offline package ready. Testing one GPS fix…');try{const p=await obtainFix();gpsLastFixAt=Date.now();setStatus(`ROAD READY · offline files verified · GPS fix ±${Math.round(p.coords.accuracy||0)} m.`);$('gpsPill').textContent='GPS verified';$('gpsPill').className='gpspill live'}catch(e){setStatus(`Offline package is ready. GPS test: ${geoErrorText(e)}`,true)}}finally{b.disabled=false;updateRoadReadiness()}}
function standaloneMode(){return !!(window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches)||navigator.standalone===true}
function gpsBlockReason(){if(!navigator.geolocation)return 'This browser does not expose GPS/geolocation.';if(!window.isSecureContext){const h=location.hostname||'this address';return `GPS is blocked because ${h} is being served over HTTP. Adding an HTTP Live Server page to the Home Screen does not make it secure. Use HTTPS for live GPS.`}if(gpsPermission==='denied')return 'Location permission is denied. Enable Location access for this site/app in your browser or phone settings.';return ''}
function updateGpsEnvironment(){const secure=window.isSecureContext,standalone=standaloneMode(),proto=location.protocol.replace(':','').toUpperCase(),host=location.hostname||'local file',perm=gpsPermission==='unknown'?'permission not checked':`permission ${gpsPermission}`;$('gpsEnv').textContent=`${secure?'Secure GPS context':'GPS blocked'} · ${standalone?'Home Screen / standalone':'browser tab'} · ${proto} ${host} · ${perm}`;$('gpsEnv').classList.toggle('warn',!secure||gpsPermission==='denied');if(!secure){$('gpsPill').textContent='GPS needs HTTPS';$('gpsPill').className='gpspill warn'}else if(!gpsRunning){$('gpsPill').textContent=gpsPermission==='denied'?'GPS denied':'GPS ready';$('gpsPill').className='gpspill'+(gpsPermission==='denied'?' warn':'')}const badge=$('appBadge');if(!(secure&&offlinePackageReady&&gpsPermission!=='denied')){badge.textContent=!secure?'● HTTPS REQUIRED':navigator.onLine?'● PREPARING':'● OFFLINE';badge.classList.toggle('warn',!secure||!offlinePackageReady)}updateRoadReadiness()}
async function refreshGpsPermission(){if(!navigator.permissions||!navigator.permissions.query){updateGpsEnvironment();return gpsPermission}try{const q=await navigator.permissions.query({name:'geolocation'});gpsPermission=q.state;q.onchange=()=>{gpsPermission=q.state;updateGpsEnvironment()}}catch(e){gpsPermission='unknown'}updateGpsEnvironment();return gpsPermission}
function geoErrorText(e){if(!e)return 'Location unavailable.';if(e.code===1)return 'Location permission was denied.';if(e.code===2)return 'The phone could not determine a GPS position.';if(e.code===3)return 'GPS is taking longer than expected.';return e.message||'Location unavailable.'}
function getOneFix(high=true){return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:high,maximumAge:high?8000:30000,timeout:high?25000:12000}))}
async function obtainFix(){try{return await getOneFix(true)}catch(first){if(first&&first.code===1)throw first;return await getOneFix(false)}}
async function requestWake(){if(!('wakeLock'in navigator)||document.visibilityState!=='visible')return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}catch(e){}}
function releaseWake(){if(wakeLock){try{wakeLock.release()}catch(e){}wakeLock=null}}
function startStaleTimer(){if(gpsStaleTimer)clearInterval(gpsStaleTimer);gpsStaleTimer=setInterval(()=>{if(!gpsRunning)return;const age=gpsLastFixAt?Date.now()-gpsLastFixAt:Infinity;if(age>30000){$('gpsPill').textContent='GPS waiting';$('gpsPill').className='gpspill warn';$('gpsDetail').textContent='GPS signal paused or stale. Keep the app visible and give the phone a clear view of the sky.'}},5000)}
function stopStaleTimer(){if(gpsStaleTimer)clearInterval(gpsStaleTimer);gpsStaleTimer=null}
function applyGpsFix(p,source='live'){const now=p.timestamp||Date.now(),previousFixAt=lastGpsAppliedAt;gpsLastFixAt=Date.now();gpsPosition={lon:p.coords.longitude,lat:p.coords.latitude,accuracy:p.coords.accuracy||0};const s=snap(gpsPosition.lon,gpsPosition.lat),acc=Math.round(gpsPosition.accuracy||0);$('gpsPill').textContent='GPS live';$('gpsPill').className='gpspill live';if(!s){$('gpsDetail').textContent=`GPS fix ±${acc}m · waiting for route match`;renderOverlay();return}const off=s.distanceKm,threshold=Math.max(.65,(gpsPosition.accuracy||0)/1000*2.2),reliable=(gpsPosition.accuracy||0)<=250;if(reliable&&off<=Math.max(2.5,threshold*3)){let next=Math.max(progress,Math.min(1,s.fraction));if(previousFixAt&&next>progress&&routeDist>0){const dt=Math.max(1,(now-previousFixAt)/1000),maxKm=dt/3600*180+1.5,maxJump=maxKm/routeDist;if(next-progress>maxJump)next=progress}trackPace(next,now,p.coords.speed);progress=next;lastGpsAppliedAt=now;update()}else{renderOverlay()}$('routeStatus').textContent=off>threshold?'Off route':'On route';$('gpsDetail').textContent=off>threshold?`OFF ROUTE · ${off.toFixed(1)} km from path · GPS ±${acc}m`:`On route · GPS ±${acc}m${!reliable?' · waiting for a better fix':etaModel.speedKmh?` · pace ${Math.round(etaModel.speedKmh)} km/h`:''}`;$('gpsDetail').classList.toggle('offroute',off>threshold);if(followGPS)centerAt(gpsPosition.lon,gpsPosition.lat)}
async function captureLocation(){await refreshGpsPermission();const blocked=gpsBlockReason();if(blocked){setStatus(blocked,true);updateGpsEnvironment();return}$('useLocation').disabled=true;$('useLocation').textContent='Locating…';setStatus('Requesting a GPS fix…');try{const p=await obtainFix();originGPS={lon:p.coords.longitude,lat:p.coords.latitude,accuracy:p.coords.accuracy||0,capturedAt:Date.now()};originMode='gps';$('from').value='Current location';const nc=nearestCommunity(originGPS.lon,originGPS.lat);$('locationHint').textContent=nc.index>=0?`near ${names[nc.index]} · GPS ±${Math.round(originGPS.accuracy)}m`:`GPS ±${Math.round(originGPS.accuracy)}m`;$('useLocation').textContent='◎ Refresh location';makeTrip()}catch(e){setStatus(geoErrorText(e),true);$('useLocation').textContent='◎ Use current location'}finally{$('useLocation').disabled=false;refreshGpsPermission()}}
async function startGPS(){if(!routeCoords.length){setStatus('Load a trip before starting GPS.',true);return}await refreshGpsPermission();const blocked=gpsBlockReason();if(blocked){setStatus(blocked,true);updateGpsEnvironment();return}if(gpsWatch!=null)return;$('gpsStart').disabled=true;$('gpsDetail').textContent='Getting a fresh start position…';let first=null;try{first=await obtainFix();if(originMode==='gps'&&currentDestIndex>=0){originGPS={lon:first.coords.longitude,lat:first.coords.latitude,accuracy:first.coords.accuracy||0,capturedAt:Date.now()};$('from').value='Current location';const nc=nearestCommunity(originGPS.lon,originGPS.lat);$('locationHint').textContent=nc.index>=0?`near ${names[nc.index]} · GPS ±${Math.round(originGPS.accuracy)}m`:`GPS ±${Math.round(originGPS.accuracy)}m`;const ok=await buildGps(names[currentDestIndex],currentDestIndex);if(!ok)throw new Error('route refresh failed')}}catch(e){setStatus(geoErrorText(e)||'Could not refresh GPS start position.',true);$('gpsStart').disabled=false;return}gpsRunning=true;followGPS=true;lastGpsAppliedAt=0;$('follow').textContent='Following';$('gpsStart').disabled=true;$('gpsStop').disabled=false;$('slider').disabled=true;$('gpsDetail').textContent='Live GPS active · keep NL Offline open while driving.';$('gpsPill').textContent='GPS starting';$('gpsPill').className='gpspill';resetEta();gpsLastFixAt=0;startStaleTimer();requestWake();if(first&&gpsRunning)applyGpsFix(first,'initial');if(!gpsRunning)return;gpsWatch=navigator.geolocation.watchPosition(p=>applyGpsFix(p,'watch'),e=>{if(e&&e.code===1){setStatus(geoErrorText(e),true);stopGPS(false);refreshGpsPermission();return}$('gpsPill').textContent='GPS waiting';$('gpsPill').className='gpspill warn';$('gpsDetail').textContent=geoErrorText(e)+' The tracker will keep trying while the app is open.'},{enableHighAccuracy:true,maximumAge:2000,timeout:20000});setStatus('Live trip running · map, route, distance and ETA are operating locally.')}
function stopGPS(clear=true){gpsRunning=false;lastGpsAppliedAt=0;if(gpsWatch!=null&&navigator.geolocation)navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null;stopStaleTimer();releaseWake();followGPS=false;$('gpsStart').disabled=false;$('gpsStop').disabled=true;$('slider').disabled=false;$('follow').textContent='Follow';if(clear){gpsPosition=null;$('gpsDetail').textContent='Slider simulates driving. Live GPS requires HTTPS and works while this app stays open.';$('gpsDetail').classList.remove('offroute');renderOverlay()}updateGpsEnvironment()}
$('prepareRoad').addEventListener('click',prepareForRoad);$('go').addEventListener('click',makeTrip);$('useLocation').addEventListener('click',captureLocation);$('from').addEventListener('input',()=>{if($('from').value.trim().toLowerCase()!=='current location'){originMode='town';originGPS=null;$('locationHint').textContent='';setTownLabels()}});$('swap').addEventListener('click',()=>{if(originMode==='gps'){originMode='town';originGPS=null;$('locationHint').textContent=''}const x=$('from').value;$('from').value=$('to').value;$('to').value=x;makeTrip()});$('slider').addEventListener('input',()=>{gpsPosition=null;progress=+$('slider').value/1000;resetEta();update()});$('gpsStart').addEventListener('click',startGPS);$('gpsStop').addEventListener('click',()=>stopGPS(true));$('follow').addEventListener('click',()=>{followGPS=!followGPS;$('follow').textContent=followGPS?'Following':'Follow';if(followGPS&&gpsPosition)centerAt(gpsPosition.lon,gpsPosition.lat)});$('fitRoute').addEventListener('click',()=>fit(routeCoords));$('zoomIn').addEventListener('click',()=>zoom(.65));$('zoomOut').addEventListener('click',()=>zoom(1.55));
const mw=$('mapwrap');mw.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,v:{...view}};mw.setPointerCapture(e.pointerId)});mw.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y,w=mw.clientWidth,h=mw.clientHeight,lon=(drag.v.maxx-drag.v.minx)*dx/Math.max(w,1),lat=(drag.v.maxy-drag.v.miny)*dy/Math.max(h,1);view={minx:drag.v.minx-lon,maxx:drag.v.maxx-lon,miny:drag.v.miny+lat,maxy:drag.v.maxy+lat};if(!rafPan)rafPan=requestAnimationFrame(()=>{rafPan=0;renderBase();renderOverlay()})});mw.addEventListener('pointerup',()=>drag=null);mw.addEventListener('pointercancel',()=>drag=null);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;updateRoadReadiness()});window.addEventListener('appinstalled',()=>{deferredInstall=null;updateRoadReadiness()});window.addEventListener('resize',size);window.addEventListener('online',()=>{updateGpsEnvironment();verifyOfflinePackage(false)});window.addEventListener('offline',updateGpsEnvironment);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){if(gpsRunning){requestWake();obtainFix().then(p=>{if(gpsRunning)applyGpsFix(p,'resume')}).catch(()=>{})}updateGpsEnvironment()}else if(gpsRunning){$('gpsDetail').textContent='App is in the background. Live GPS may pause until NL Offline is visible again.'}});window.addEventListener('pageshow',()=>{updateGpsEnvironment();if(gpsRunning)obtainFix().then(p=>{if(gpsRunning)applyGpsFix(p,'resume')}).catch(()=>{})});async function boot(){restoreTripPrefs();size();await refreshGpsPermission();updateGpsEnvironment();if('serviceWorker'in navigator&&window.isSecureContext){try{const reg=await navigator.serviceWorker.register('./sw.js?v=0.9',{scope:'./'});await navigator.serviceWorker.ready;reg.update().catch(()=>{});await verifyOfflinePackage(false)}catch(e){offlinePackageReady=false;updateRoadReadiness({error:e.message})}}else updateRoadReadiness();setStatus(`Ready · ${DATA.level1Count} places · ${DATA.level2Count||DATA.routeReady} mapped locally.`);makeTrip()}boot();